version: 2.1

executors:
  docker-executor:
    docker:
      - image: circleci/python:3.8
    working_directory: ~/repo

jobs:
  build:
    executor: docker-executor
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.7
      - run:
          name: Install AWS CLI
          command: |
            sudo apt-get update
            sudo apt-get install -y awscli

      - run:
          name: Configure AWS CLI
          command: |
            aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
            aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
            aws configure set default.region us-east-2

      - run:
          name: Login to Amazon ECR
          command: |
            aws ecr get-login-password --region us-east-2 | docker login --username AWS --password-stdin 276183208465.dkr.ecr.us-east-2.amazonaws.com

      - run:
          name: Build Docker Image
          command: |
            docker build -t ahj-final-ecs-ecr .

      - run:
          name: Tag Docker Image
          command: |
            docker tag ahj-final-ecs-ecr:latest 276183208465.dkr.ecr.us-east-2.amazonaws.com/ahj-final-ecs-ecr:latest

      - run:
          name: Push Docker Image to ECR
          command: |
            docker push 276183208465.dkr.ecr.us-east-2.amazonaws.com/ahj-final-ecs-ecr:latest

      - run:
          name: Update ECS Service
          command: |
            aws ecs update-service --cluster ahj-final-ecs-cluster --service ahj-final-ecs-service --force-new-deployment

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
